#this file is shared between global and local cost map
max_obstacle_height: 0.6 #2.0

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
# robot_radius: 0.295  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
#calculated from the center of the chasis
footprint: [[0.3,0.225 ], [0.3,-0.225,], [-0.3,0.225], [-0.3,-0.225 ]]
#footprint_padding: 0.01

#global_costmap is the saved map with inflation layer
#loca_costmap is adding inflation layer to dynamic obsticals for the robot while in operation
#global_planner make path planning with static obsticals
#local_planner make path planning with dynamic obsticals

laser_layer:
  observation_sources:  scan #scan for lidar. image for camre
  scan:
    data_type: LaserScan #from sensor_msgs/LaserScan.msg package
    topic: /my_robot/laser/scan
    marking: true  #for dynamic obsticals
    clearing: true #for dynamic obsticals
    min_obstacle_height: 0.05
    max_obstacle_height: 0.35
    #the robot won't see any obsticals further this point
    obstacle_range: 4.0
    raytrace_range: 5.0
  # for debugging only, let's you see the entire voxel grid

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  10  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     8  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic: map
  subscribe_to_updates: true
  track_unknown_space:  true
