local_costmap:
  global_frame: odom
  robot_base_frame: /base_footprint
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: false #as it deals with dynamic obsticals and not the static in global costmap
  rolling_window: true #as it deals with dynamic obsticals.

  #the area around the robot to scan the dynamic obsticals in
  width: 3.0
  height: 3.0
   
  resolution: 0.025
  transform_tolerance: 0.5

  plugins:
   - {name: laser_layer,         type: "costmap_2d::ObstacleLayer"} 
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
   
