# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

# How many times to allow for planning retries before executing recovery behaviors. Default: -1.0 (infinite retries)

# controller_frequency defines how frequently the local plan is updated
controller_frequency: 10.0
controller_patience: 3.0

# planner_frequency defines how frequently the global plan is calculated
# set to 0.0 to prevent move_base to feed a fixed plan again and again and cause the robot to oscillate
planner_frequency: 5.0 # 0.5
planner_patience: 5.0

oscillation_timeout: 30.0 # A value of 0.0 corresponds to an infinite timeout: no timer counting up to execute recovery behaviors
oscillation_distance: 0.2


# i have three algorithms for global planner 1)carrot_planner 2)navfn 3)Global_planner
# i have files for the 2 algorithms of them, and i will choose which one to use 
# from the following command
#alternatives: "navfn/NavfnROS", carrot_planner/CarrotPlanner
base_global_planner: "global_planner/GlobalPlanner"
# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"
